"""
SkillTemplates — 技能模板库
提供各类技能的 SKILL.md 模板和目录结构
"""

from datetime import datetime


class SkillTemplates:
    """技能模板"""
    
    # 标准技能模板
    BASIC_SKILL_TEMPLATE = '''---
name: {skill_name}
description: "{description}"
category: {category}
tags: [{tags}]
---

# {skill_name}

{description}

## 触发场景

触发条件（满足任一即激活）：
{trigger_conditions}

## 能力清单

{capabilities}

## 使用方式

### 基本用法

```bash
{usage_example}
```

## 输入输出

**输入：**
{inputs}

**输出：**
{outputs}

## 注意事项

{notes}

## 示例

### 示例1: {example1_title}

```
{example1_content}
```

---

*由梦境技能自动生成 | 生成时间: {timestamp}*
'''

    # Python 脚本技能模板
    PYTHON_SKILL_TEMPLATE = '''---
name: {skill_name}
description: "{description}"
category: {category}
tags: [{tags}]
---

# {skill_name}

{description}

## 触发场景

{trigger_conditions}

## 核心能力

{capabilities}

## 脚本使用

```bash
python3 scripts/{script_name}.py {script_args}
```

## 参数说明

{parameters}

## 输出格式

{outputs}

## 依赖

{dependencies}

---

*Auto-generated by Dream Extension | {timestamp}*
'''

    @classmethod
    def generate_skill_md(cls, skill_name: str, description: str, category: str,
                          triggers: list, capabilities: list, **kwargs) -> str:
        """生成标准 SKILL.md 内容"""
        
        timestamp = datetime.now().strftime('%Y-%m-%d %H:%M')
        tags = kwargs.get('tags', [category])
        
        # 构建触发条件
        trigger_lines = []
        for i, trigger in enumerate(triggers, 1):
            trigger_lines.append(f"{i}. {trigger}")
        trigger_conditions = '\n'.join(trigger_lines) if trigger_lines else "（待定义）"
        
        # 构建能力清单
        capability_lines = []
        for cap in capabilities:
            capability_lines.append(f"- {cap}")
        capabilities_text = '\n'.join(capability_lines) if capability_lines else "（待定义）"
        
        # 构建输入输出
        inputs = kwargs.get('inputs', ['（待定义）'])
        outputs = kwargs.get('outputs', ['（待定义）'])
        
        inputs_text = '\n'.join([f"- {inp}" for inp in inputs])
        outputs_text = '\n'.join([f"- {out}" for out in outputs])
        
        return cls.BASIC_SKILL_TEMPLATE.format(
            skill_name=skill_name,
            description=description,
            category=category,
            tags=', '.join(tags),
            timestamp=timestamp,
            trigger_conditions=trigger_conditions,
            capabilities=capabilities_text,
            usage_example=kwargs.get('usage_example', '（待定义）'),
            inputs=inputs_text,
            outputs=outputs_text,
            notes=kwargs.get('notes', '无特殊注意事项'),
            example1_title=kwargs.get('example1_title', '基础用法'),
            example1_content=kwargs.get('example1_content', '# 示例代码'),
        )
    
    @classmethod
    def generate_python_skill(cls, skill_name: str, description: str, category: str,
                              script_name: str, capabilities: list, **kwargs) -> dict:
        """生成 Python 技能的结构"""
        
        timestamp = datetime.now().strftime('%Y-%m-%d %H:%M')
        tags = kwargs.get('tags', [category])
        
        # SKILL.md 内容
        skill_md = cls.PYTHON_SKILL_TEMPLATE.format(
            skill_name=skill_name,
            description=description,
            category=category,
            tags=', '.join(tags),
            timestamp=timestamp,
            trigger_conditions=kwargs.get('trigger_conditions', '（待定义）'),
            capabilities='\n'.join([f"- {c}" for c in capabilities]),
            script_name=script_name,
            script_args=kwargs.get('script_args', '--help'),
            parameters=kwargs.get('parameters', '（待定义）'),
            outputs=kwargs.get('outputs', '（待定义）'),
            dependencies=kwargs.get('dependencies', '无外部依赖'),
        )
        
        # 主脚本模板
        main_script = f'''#!/usr/bin/env python3
"""
{skill_name} - {description}
自动生成的脚本
"""

import argparse
import sys

def main():
    parser = argparse.ArgumentParser(description='{description}')
    # 添加参数
    {kwargs.get('arg_template', "parser.add_argument('--help', action='help')")}
    
    args = parser.parse_args()
    
    # 核心逻辑
    print("Hello from {skill_name}!")
    
    return 0

if __name__ == '__main__':
    sys.exit(main())
'''
        
        return {
            'SKILL.md': skill_md,
            f'scripts/{script_name}.py': main_script,
        }


class SkillDirectoryStructure:
    """技能目录结构模板"""
    
    BASIC_STRUCTURE = {
        'SKILL.md': '技能文档',
        'scripts/': '核心脚本目录',
    }
    
    ADVANCED_STRUCTURE = {
        'SKILL.md': '技能文档',
        'scripts/': '核心脚本目录',
        'references/': '参考文档目录',
        'assets/': '资源文件目录',
        'templates/': '模板文件目录',
    }
    
    @classmethod
    def get_structure(cls, complexity: str = 'basic') -> dict:
        """获取目录结构"""
        if complexity == 'advanced':
            return cls.ADVANCED_STRUCTURE
        return cls.BASIC_STRUCTURE
    
    @classmethod
    def validate_path(cls, path: str) -> bool:
        """验证路径是否安全"""
        # 禁止的路径模式
        forbidden = ['../', '~/', '/etc/', '/usr/', '/root/']
        for pattern in forbidden:
            if pattern in path:
                return False
        return True
